### ISSUE TITLE
Questions about hyperparameter tuning

### ISSUE THREAD

**Issue by wendy2003888** [clabrugere/wukong-recommendation#1]
Hi Authors,

Congrats on your excellent work. I am Wendy, a Machine Learning Engineer, and I am doing experiments with Wukong layers, comparing them to DCNv2.

I am curious about the rule-of-thumb for tuning hyperparameters for Wukong layers. On the last page of your paper, Table 3 presents a performance comparison across different model architectures. However, given a dataset's sample size and number of features, are there any recommended simple rules for determining the range of hyperparameters (e.g., number of layers, number of hidden layers/heads, ml: lcb dimension, nf: fmb dimension, k-rank, etc.)?

Thank you in advance for your guidance.

**Comment by clabrugere** [comment]
Hello Wendy, I'm not one of the authors and this is an unofficial implementation of the paper (afaik authors didn't publish their code) so I didn't run the extensive experiments they have.

For the number of embeddings in the LCB and FMB layers as well as the rank k, I think those really depend on the data. Note that the values reported in the table on the last page are from experiments on a very large closed source dataset so it's hard to extrapolate to other datasets. Interestingly, they seem to always set nL = nF = k though.
I would suggest to run some experiments on your specific data to find good values having in mind that you probably don't need as many parameters.

For the number of interaction layers, except if you have huge datasets, between 2 and 4 layers is enough from experience. Similarly, the number of hidden layers in the last MLP is probably fine at 2 or 3.

**Comment by wendy2003888** [comment]
Oh, I see. Thanks Clément!  
I tried a few combinations of nL, nf, and k based on the paper. However, I am still experimenting with the num_wukong_layers and num_hidden_wukong in the Wukong block. I will experiment with more setups.
Thank you for your fast response. The implementation is awesome! I will close this thread.
